### ISSUE TITLE
Texture atlas for UI components

### ISSUE THREAD

**Issue by MyRealityCoding** [bitbrain-gaming/craft#11]
Introduce a texture atlas for UI components in order to save loading time.

**Comment by MyRealityCoding** [comment]
Regarding to this output the actual RAM is full. We need texture atlas to reduce memory usage.
```text
01-12 22:06:03.558: I/INFO(8340): Craft v. 0.6.10 (dev)
01-12 22:06:03.558: I/INFO(8340): Registering tweens...
01-12 22:06:03.568: I/INFO(8340): Tween accessors registered.
01-12 22:06:03.568: I/INFO(8340): External directory found.
01-12 22:06:03.568: I/INFO(8340): Datasource found.
01-12 22:06:03.568: I/LOAD(8340): Loading bundles...
01-12 22:06:03.568: I/INFO(8340): Set locale to 'en'
01-12 22:06:03.619: D/dalvikvm(8340): GC_FOR_ALLOC freed 351K, 5% free 9425K/9840K, paused 18ms, total 18ms
01-12 22:06:03.649: I/INFO(8340): Done loading bundles.
01-12 22:06:03.649: I/LOAD(8340): Load game data..
01-12 22:06:03.679: I/INFO(8340): Player profile found.
01-12 22:06:03.699: I/INFO(8340): Migration 'de.bitbrain.craft.migration.jobs.ItemMigrationJob::release_items' found.
01-12 22:06:03.719: I/INFO(8340): Migration 'de.bitbrain.craft.migration.jobs.OwnedItemMigrationJob::release_items' found.
01-12 22:06:03.739: I/INFO(8340): Migration 'de.bitbrain.craft.migration.jobs.RecipeMigrationJob::release_items' found.
01-12 22:06:03.769: D/dalvikvm(8340): GC_FOR_ALLOC freed 296K, 4% free 9642K/9972K, paused 16ms, total 16ms
01-12 22:06:03.779: I/INFO(8340): Migration 'de.bitbrain.craft.migration.jobs.LearnedRecipeMigrationJob::release_items' found.
01-12 22:06:05.090: I/LOAD(8340): Font 'fonts/larger.fnt' loaded.
01-12 22:06:05.150: D/dalvikvm(8340): GC_FOR_ALLOC freed 436K, 5% free 9716K/10188K, paused 15ms, total 18ms
01-12 22:06:05.170: D/dalvikvm(8340): GC_FOR_ALLOC freed 45K, 5% free 9703K/10188K, paused 18ms, total 18ms
01-12 22:06:05.170: I/dalvikvm-heap(8340): Grow heap (frag case) to 9.755MB for 262204-byte allocation
01-12 22:06:05.190: D/dalvikvm(8340): GC_FOR_ALLOC freed <1K, 5% free 9959K/10448K, paused 17ms, total 17ms
01-12 22:06:05.200: I/LOAD(8340): Font 'fonts/medium.fnt' loaded.
01-12 22:06:05.230: D/dalvikvm(8340): GC_FOR_ALLOC freed 357K, 8% free 9715K/10448K, paused 14ms, total 14ms
01-12 22:06:05.250: I/LOAD(8340): Font 'fonts/mono.fnt' loaded.
01-12 22:06:05.350: D/dalvikvm(8340): GC_FOR_ALLOC freed 473K, 7% free 9733K/10448K, paused 18ms, total 19ms
01-12 22:06:05.360: I/LOAD(8340): Font 'fonts/small.fnt' loaded.
01-12 22:06:05.390: D/dalvikvm(8340): GC_FOR_ALLOC freed 354K, 7% free 9741K/10448K, paused 14ms, total 14ms
01-12 22:06:05.410: I/LOAD(8340): Particle Effect 'particles/particles-green-small.p' loaded.
01-12 22:06:05.470: I/LOAD(8340): Sound 'audio/abort.mp3' loaded.
01-12 22:06:05.520: I/LOAD(8340): Sound 'audio/button_01.mp3' loaded.
01-12 22:06:05.580: I/LOAD(8340): Sound 'audio/confirm.mp3' loaded.
01-12 22:06:05.631: I/LOAD(8340): Sound 'audio/pop.mp3' loaded.
01-12 22:06:05.691: I/LOAD(8340): Sound 'audio/tab.mp3' loaded.
01-12 22:06:05.861: I/LOAD(8340): Texture 'images/icons/ico_alchemy_flasks_overview.png' loaded.
01-12 22:06:05.911: I/LOAD(8340): Texture 'images/background.png' loaded.
01-12 22:06:05.971: I/LOAD(8340): Texture 'images/button.png' loaded.
01-12 22:06:05.981: D/dalvikvm(8340): GC_FOR_ALLOC freed 495K, 7% free 9754K/10448K, paused 14ms, total 14ms
01-12 22:06:06.021: I/LOAD(8340): Texture 'images/button_down.png' loaded.
01-12 22:06:06.071: I/LOAD(8340): Texture 'images/button_red.png' loaded.
01-12 22:06:06.131: I/LOAD(8340): Texture 'images/button_red_down.png' loaded.
01-12 22:06:06.191: I/LOAD(8340): Texture 'images/cursor.png' loaded.
01-12 22:06:06.241: I/LOAD(8340): Texture 'images/icons/ico_fab_power_medium.png' loaded.
01-12 22:06:06.301: I/LOAD(8340): Texture 'images/icons/ico_jewel_diamond_medium.png' loaded.
01-12 22:06:06.351: I/LOAD(8340): Texture 'images/logo.png' loaded.
01-12 22:06:06.411: I/LOAD(8340): Texture 'images/ui/panel.9.png' loaded.
01-12 22:06:06.471: I/LOAD(8340): Texture 'images/ui/panel_black.9.png' loaded.
01-12 22:06:06.521: I/LOAD(8340): Texture 'images/ui/panel_highlight.9.png' loaded.
01-12 22:06:06.581: I/LOAD(8340): Texture 'images/panel_small_horizontal.png' loaded.
01-12 22:06:06.631: I/LOAD(8340): Texture 'images/panel_small_light_horizontal.png' loaded.
01-12 22:06:06.692: I/LOAD(8340): Texture 'images/ui/panel_tab.9.png' loaded.
01-12 22:06:06.752: I/LOAD(8340): Texture 'images/ui/panel_tab_active.9.png' loaded.
01-12 22:06:06.802: I/LOAD(8340): Texture 'images/ui/panel_transparent.9.png' loaded.
01-12 22:06:06.862: I/INFO(8340): Done loading assets.
01-12 22:06:06.892: D/dalvikvm(8340): GC_FOR_ALLOC freed 468K, 7% free 9770K/10448K, paused 14ms, total 14ms
01-12 22:06:08.864: D/dalvikvm(8340): GC_FOR_ALLOC freed 441K, 6% free 9828K/10448K, paused 14ms, total 15ms
01-12 22:06:10.665: D/dalvikvm(8340): GC_FOR_ALLOC freed 465K, 6% free 9875K/10448K, paused 15ms, total 15ms
01-12 22:06:10.866: D/dalvikvm(8340): GC_FOR_ALLOC freed 396K, 5% free 9990K/10448K, paused 20ms, total 20ms
01-12 22:06:11.006: I/INFO(8340): Attached element with id='item_flux' to VerticalGroup
01-12 22:06:11.036: D/dalvikvm(8340): GC_FOR_ALLOC freed 415K, 5% free 10086K/10536K, paused 20ms, total 20ms
01-12 22:06:11.056: I/INFO(8340): Attached element with id='item_xenocite' to VerticalGroup
01-12 22:06:11.076: I/INFO(8340): Attached element with id='item_sulfur' to VerticalGroup
01-12 22:06:11.096: I/INFO(8340): Attached element with id='item_acid_1' to VerticalGroup
01-12 22:06:11.116: I/INFO(8340): Attached element with id='item_water' to VerticalGroup
01-12 22:06:11.136: I/INFO(8340): Attached element with id='item_jewel_diamond_medium' to VerticalGroup
01-12 22:06:11.176: D/dalvikvm(8340): GC_FOR_ALLOC freed 466K, 5% free 10116K/10624K, paused 18ms, total 18ms
01-12 22:06:11.206: D/dalvikvm(8340): GC_FOR_ALLOC freed 96K, 6% free 10089K/10624K, paused 15ms, total 15ms
01-12 22:06:11.206: I/dalvikvm-heap(8340): Grow heap (frag case) to 9.946MB for 65552-byte allocation
01-12 22:06:11.226: D/dalvikvm(8340): GC_FOR_ALLOC freed <1K, 6% free 10153K/10692K, paused 18ms, total 18ms
01-12 22:06:11.296: W/dalvikvm(8340): threadid=16: thread exiting with uncaught exception (group=0x4158dba8)
01-12 22:06:11.296: E/AndroidRuntime(8340): FATAL EXCEPTION: GLThread 2717
01-12 22:06:11.296: E/AndroidRuntime(8340): Process: de.bitbrain.craft.android, PID: 8340
01-12 22:06:11.296: E/AndroidRuntime(8340): com.badlogic.gdx.utils.GdxRuntimeException: Asset not loaded: images/ui/tab_gradient.png
01-12 22:06:11.296: E/AndroidRuntime(8340): 	at com.badlogic.gdx.assets.AssetManager.get(AssetManager.java:125)
01-12 22:06:11.296: E/AndroidRuntime(8340): 	at de.bitbrain.craft.SharedAssetManager.get(SharedAssetManager.java:52)
01-12 22:06:11.296: E/AndroidRuntime(8340): 	at de.bitbrain.craft.ui.widgets.TabWidget$Tab.draw(TabWidget.java:248)
01-12 22:06:11.296: E/AndroidRuntime(8340): 	at com.badlogic.gdx.scenes.scene2d.Group.drawChildren(Group.java:111)
01-12 22:06:11.296: E/AndroidRuntime(8340): 	at com.badlogic.gdx.scenes.scene2d.Group.draw(Group.java:58)
01-12 22:06:11.296: E/AndroidRuntime(8340): 	at com.badlogic.gdx.scenes.scene2d.ui.WidgetGroup.draw(WidgetGroup.java:154)
01-12 22:06:11.296: E/AndroidRuntime(8340): 	at com.badlogic.gdx.scenes.scene2d.Group.drawChildren(Group.java:124)
01-12 22:06:11.296: E/AndroidRuntime(8340): 	at com.badlogic.gdx.scenes.scene2d.Group.draw(Group.java:58)
01-12 22:06:11.296: E/AndroidRuntime(8340): 	at com.badlogic.gdx.scenes.scene2d.ui.WidgetGroup.draw(WidgetGroup.java:154)
01-12 22:06:11.296: E/AndroidRuntime(8340): 	at com.badlogic.gdx.scenes.scene2d.ui.Table.draw(Table.java:123)
01-12 22:06:11.296: E/AndroidRuntime(8340): 	at com.badlogic.gdx.scenes.scene2d.Group.drawChildren(Group.java:111)
01-12 22:06:11.296: E/AndroidRuntime(8340): 	at com.badlogic.gdx.scenes.scene2d.Group.draw(Group.java:58)
01-12 22:06:11.296: E/AndroidRuntime(8340): 	at com.badlogic.gdx.scenes.scene2d.Stage.draw(Stage.java:128)
01-12 22:06:11.296: E/AndroidRuntime(8340): 	at de.bitbrain.craft.graphics.UIRenderer.render(UIRenderer.java:176)
01-12 22:06:11.296: E/AndroidRuntime(8340): 	at de.bitbrain.craft.screens.AbstractScreen.render(AbstractScreen.java:114)
01-12 22:06:11.296: E/AndroidRuntime(8340): 	at com.badlogic.gdx.Game.render(Game.java:46)
01-12 22:06:11.296: E/AndroidRuntime(8340): 	at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:416)
01-12 22:06:11.296: E/AndroidRuntime(8340): 	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1523)
01-12 22:06:11.296: E/AndroidRuntime(8340): 	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1240)
```
